name: Cypress Tests

on:
  push:
    branches-ignore:
      - "renovate/**"

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17 # Upgrade to the required version
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8


      - name: Update pnpm lockfile
        run: pnpm install --no-frozen-lockfile

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Set environment variables
        run: |
          echo NEXTAUTH_SECRET=$NEXTAUTH_SECRET >> .env.local
          echo NEXTAUTH_URL=$NEXTAUTH_URL >> .env.local
          echo WEBSITE_URL=${{ secrets.WEBSITE_URL }} >> .env.local

      - name: Build Next.js Project
        run: pnpm build

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .next
          compression-level: 6 # Optional compression level (higher = smaller size)
          overwrite: false # Optional, don't overwrite existing artifacts
          if-no-files-found: error

  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    needs: install

    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving Cypress Cloud hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Update pnpm lockfile
        run: pnpm install --no-frozen-lockfile

      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .next

      - name: Run development server
        run: pnpm dev
        
      - name: "UI Tests - Chrome"
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
      - uses: cypress-io/github-action@v6
        with:
          # runTests: false
          # start: pnpm start
          # wait-on: "http://localhost:3000"
          # wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          # group: "UI - Chrome"
          # spec: cypress/tests/ui/*
          config-file: cypress.config.ts
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
