name: Cypress End-To-End Tests
on: [push]

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-

      - name: Build initial core (Focused on core creation)
        run: npm run build:core

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: core-build
          path: dist/core

  cypress-run:
    runs-on: ubuntu-latest
    needs: install-and-build
    steps:
      - uses: actions/checkout@v4

      - name: Download core build artifacts
        uses: actions/download-artifact@v4
        with:
          name: core-build

      - name: Run Cypress tests (Using pre-built core)
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: "http://localhost:3000"
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
