name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Caching step added here
    - name: Cache additional dependencies
      uses: actions/cache@v4.0.2
      with:
        path: |
          **/node_modules
          **/.eslintcache
          **/.npm
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run cypress
